version: '3.6'

services:
  # ---------------------------------------------------------------------------
  # PostgreSQL
  # ---------------------------------------------------------------------------
  database:
    container_name: loxagon
    image: postgres:13.1
    environment:
      POSTGRES_USER: davi
      POSTGRES_PASSWORD: davi
      POSTGRES_DB: loxagon
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes: 
  database-data:
    driver: local
